// Gano Digital — Catalog data v2
// Filtro: solo productos MEDIO y ALTO de cada categoría
// EXCLUIDOS: start-wp (hosting básico), dom-com (dominio básico)
// Precios en COP.

window.GANO_PRODUCTS = [
  // ======= HOSTING WORDPRESS — MEDIO =======
  {
    id: 'pro-managed',
    category: 'hosting',
    tier_rank: 'medio',
    objectives: ['corporativo', 'blog', 'portafolio'],
    tier: 'Avanzado · WordPress',
    name: 'Pro Managed',
    icon: 'fa-microchip',
    tagline: 'Sitios multipágina con tráfico serio. Staging, CDN y cacheo de objetos.',
    pitch: 'Cuando tu sitio empieza a recibir visitas reales y no puedes permitirte caídas los lunes. Incluye ambiente de pruebas para que nada rompa en producción.',
    monthly: 39000,
    yearly: 390000,
    badge: null,
    featured: false,
    features: [
      { label: 'Almacenamiento', value: '75 GB NVMe' },
      { label: 'Sitios WP', value: '3' },
      { label: 'Tráfico mensual', value: 'Hasta 150.000 visitas' },
      { label: 'Staging', value: 'Incluido' },
      { label: 'CDN', value: 'Global · 200+ POPs' },
      { label: 'Object Cache', value: 'Redis dedicado' },
      { label: 'Backups', value: 'Cada 12 h · 30 días' },
      { label: 'Emails', value: '5 cuentas' },
    ],
    specs: {
      cpu: '4 vCPU compartido',
      ram: '4 GB',
      io: 'NVMe Gen4 · 5.200 MB/s',
      tls: 'TLS 1.3 · HSTS',
      waf: 'Capa 7 · reglas personalizadas',
      sla: '99.95%',
    },
    bestFor: ['Sitio corporativo multipágina', 'Blog con tráfico creciente', 'Agencia con 2-3 clientes'],
  },
  // ======= HOSTING WORDPRESS — ALTO (estrella) =======
  {
    id: 'business-nvme',
    category: 'hosting',
    tier_rank: 'alto',
    objectives: ['ecommerce', 'corporativo'],
    tier: 'E-commerce · NVMe Gen4',
    name: 'Business NVMe',
    icon: 'fa-bolt',
    tagline: 'Velocidad crítica para WooCommerce de alta autoridad. SLA 99.95%.',
    pitch: 'Construido para WooCommerce serio. Cada milisegundo ahorrado en checkout es un 1% más de conversión. Aquí ahorramos cientos.',
    monthly: 89000,
    yearly: 890000,
    featured: true,
    badge: 'Popular',
    features: [
      { label: 'Almacenamiento', value: '150 GB NVMe Gen4' },
      { label: 'Sitios WP', value: '10' },
      { label: 'Tráfico mensual', value: 'Hasta 500.000 visitas' },
      { label: 'WAF Capa 7', value: 'Activo · reglas WooCommerce' },
      { label: 'CDN', value: 'Global Premium' },
      { label: 'Object Cache', value: 'Redis dedicado 1 GB' },
      { label: 'Backups', value: 'Cada 6 h · 60 días' },
      { label: 'Emails', value: '20 cuentas' },
    ],
    specs: {
      cpu: '8 vCPU prioritario',
      ram: '8 GB',
      io: 'NVMe Gen4 · 7.500 MB/s',
      tls: 'TLS 1.3 · Post-Q opt-in',
      waf: 'Capa 7 avanzado · bot mitigation',
      sla: '99.95%',
    },
    bestFor: ['Tienda WooCommerce con ≥200 productos', 'Marca con campañas pagas activas', 'Sitio con picos de tráfico'],
  },
  // ======= HOSTING WORDPRESS — ALTO ÉLITE =======
  {
    id: 'ultimate',
    category: 'hosting',
    tier_rank: 'alto',
    objectives: ['agencia', 'corporativo', 'ecommerce'],
    tier: 'Élite · WordPress',
    name: 'Ultimate',
    icon: 'fa-crown',
    tagline: 'Todo incluido: correo, SSL wildcard, monitoreo proactivo y consultoría mensual.',
    pitch: 'Para cuando tu operación digital ya no admite improvisación. Ingeniero SOTA asignado, revisión mensual y todo el ecosistema servido en bandeja.',
    monthly: 148000,
    yearly: 1480000,
    featured: false,
    badge: 'Élite',
    features: [
      { label: 'Almacenamiento', value: 'Ilimitado NVMe' },
      { label: 'Sitios WP', value: 'Ilimitados' },
      { label: 'Tráfico mensual', value: 'Sin tope · fair use' },
      { label: 'SSL Wildcard', value: 'Incluido' },
      { label: 'Consultoría', value: '1 h mensual · ingeniero SOTA' },
      { label: 'Monitoreo', value: '24/7 proactivo' },
      { label: 'Backups', value: 'Cada 4 h · 90 días' },
      { label: 'Emails', value: 'Ilimitados · anti-phishing' },
    ],
    specs: {
      cpu: '16 vCPU dedicado',
      ram: '16 GB',
      io: 'NVMe Gen4 · 7.500 MB/s dedicado',
      tls: 'TLS 1.3 · Post-Q por defecto',
      waf: 'Capa 7 · reglas custom por cliente',
      sla: '99.98%',
    },
    bestFor: ['Agencia con 10+ clientes', 'Marca corporativa con operación crítica', 'Ecosistema multi-tienda'],
  },

  // ======= VPS — ÚNICO (siempre mostrar) =======
  {
    id: 'vps-alpha',
    category: 'vps',
    tier_rank: 'alto',
    objectives: ['agencia', 'corporativo', 'ecommerce'],
    tier: 'Máxima soberanía',
    name: 'VPS Pro Alpha',
    icon: 'fa-server',
    tagline: 'Nodo dedicado, orquestación manual por ingeniero SOTA asignado.',
    pitch: 'Tu propia fortaleza. Acceso root completo, stack a medida, y un ingeniero SOTA que conoce tu proyecto por nombre.',
    monthly: 250000,
    yearly: 2500000,
    featured: false,
    badge: 'SOTA',
    features: [
      { label: 'vCPU', value: '8 cores dedicados' },
      { label: 'RAM', value: '32 GB DDR5' },
      { label: 'Almacenamiento', value: '500 GB NVMe Gen4' },
      { label: 'Ancho de banda', value: '10 TB/mes' },
      { label: 'Acceso root', value: 'Completo · SSH' },
      { label: 'Panel', value: 'cPanel o Plesk (opcional)' },
      { label: 'Ingeniero', value: 'SOTA dedicado asignado' },
      { label: 'SLA', value: '99.99%' },
    ],
    specs: {
      cpu: '8 vCPU AMD EPYC dedicados',
      ram: '32 GB DDR5 ECC',
      io: 'NVMe Gen4 · 7.500 MB/s RAID10',
      tls: 'TLS 1.3 · Post-Q configurable',
      waf: 'A medida · kernel-level opt',
      sla: '99.99%',
    },
    bestFor: ['Operación enterprise', 'SaaS en Colombia', 'Múltiples tiendas WooCommerce'],
  },

  // ======= DOMINIOS — SOLO .CO (el alto) =======
  {
    id: 'dom-co',
    category: 'dominio',
    tier_rank: 'alto',
    objectives: ['blog', 'portafolio', 'corporativo', 'ecommerce', 'agencia'],
    tier: 'Dominios · Reseller',
    name: 'Dominio .co',
    icon: 'fa-globe',
    tagline: 'Registro colombiano con privacidad WHOIS incluida y DNS premium.',
    pitch: 'El TLD que grita "hecho en Colombia". Viene con privacidad WHOIS, DNS premium y SSL básico de serie.',
    monthly: null,
    yearly: 89000,
    featured: false,
    badge: null,
    features: [
      { label: 'TLD disponibles', value: '.co / .com.co / .digital' },
      { label: 'Privacidad WHOIS', value: 'Incluida gratis' },
      { label: 'DNS premium', value: 'Anycast global' },
      { label: 'SSL básico', value: 'Gratis de por vida' },
      { label: 'Forwarding', value: 'URL + email' },
      { label: 'Transferencia', value: 'Sin costo' },
    ],
    specs: {
      registrar: 'GoDaddy Reseller · acreditado ICANN',
      dns: 'Anycast · 6 POPs globales',
      lock: 'Registry lock disponible',
    },
    bestFor: ['Marca colombiana', 'Proyecto que quiere identidad local', 'Complementar cualquier plan de hosting'],
  },

  // ======= SEGURIDAD — AMBOS (MEDIO + ALTO) =======
  {
    id: 'waf-pro',
    category: 'seguridad',
    tier_rank: 'medio',
    objectives: ['ecommerce', 'corporativo', 'agencia'],
    tier: 'Blindaje · WAF',
    name: 'WAF Capa 7 Premium',
    icon: 'fa-lock',
    tagline: 'Firewall de aplicación con reglas curadas por ingenieros SOTA.',
    pitch: 'Bloqueo inteligente de bots, SQL injection, XSS y scraping agresivo. Reglas que evolucionan con las amenazas reales de Colombia.',
    monthly: 45000,
    yearly: 450000,
    featured: false,
    badge: null,
    features: [
      { label: 'Nivel OSI', value: 'Capa 7 (aplicación)' },
      { label: 'Reglas', value: 'OWASP Top 10 + custom Gano' },
      { label: 'Bot mitigation', value: 'ML · huella de comportamiento' },
      { label: 'Rate limit', value: 'Por endpoint · configurable' },
      { label: 'DDoS', value: 'Hasta 10 Gbps mitigado' },
      { label: 'Dashboard', value: 'Live · exportable' },
    ],
    specs: {
      engine: 'ModSecurity + ML propietario',
      updates: 'Reglas actualizadas cada 24h',
      latency: '< 3 ms añadido',
    },
    bestFor: ['Tienda con historial de intentos de fraude', 'Sitio con formularios públicos', 'Portal con login'],
  },
  {
    id: 'ssl-pro',
    category: 'seguridad',
    tier_rank: 'alto',
    objectives: ['ecommerce', 'corporativo'],
    tier: 'Blindaje · SSL',
    name: 'SSL Wildcard Pro',
    icon: 'fa-shield-halved',
    tagline: 'Certificado EV + Wildcard. Firma criptográfica visible en navegador.',
    pitch: 'Validación Extendida más cobertura Wildcard para todos tus subdominios. La señal de confianza que tu checkout necesita.',
    monthly: null,
    yearly: 340000,
    featured: false,
    badge: null,
    features: [
      { label: 'Validación', value: 'Extendida (EV)' },
      { label: 'Cobertura', value: 'Wildcard · *.tudominio.com' },
      { label: 'Cifrado', value: 'SHA-256 · 2048-bit' },
      { label: 'Garantía', value: 'USD $1.750.000' },
      { label: 'Soporte', value: '24/7 por chat' },
      { label: 'Reemisión', value: 'Ilimitada' },
    ],
    specs: {
      ca: 'Sectigo / DigiCert',
      algorithm: 'SHA-256 RSA 2048',
      tls: 'TLS 1.2 / 1.3',
    },
    bestFor: ['E-commerce con pasarela propia', 'Portal corporativo con login', 'Fintech / sector regulado'],
  },

  // ======= EMAIL — ÚNICO =======
  {
    id: 'email-pro',
    category: 'email',
    tier_rank: 'medio',
    objectives: ['corporativo', 'ecommerce', 'agencia'],
    tier: 'Correo corporativo',
    name: 'Email Pro',
    icon: 'fa-envelope-open-text',
    tagline: 'Buzones profesionales con tu dominio. Anti-phishing y archivo legal.',
    pitch: '25 GB por buzón, anti-spam agresivo y retención legal de 7 años para sectores regulados.',
    monthly: 12000,
    yearly: 120000,
    featured: false,
    badge: null,
    features: [
      { label: 'Espacio', value: '25 GB por buzón' },
      { label: 'Cuentas incluidas', value: '5 buzones' },
      { label: 'Dominio propio', value: 'Configurado sin costo' },
      { label: 'Protocolo', value: 'IMAP · POP3 · SMTP · Exchange' },
      { label: 'Anti-phishing', value: 'DMARC · DKIM · SPF' },
      { label: 'Móvil', value: 'iOS · Android sincronizado' },
      { label: 'Archivo legal', value: '7 años (opcional)' },
    ],
    specs: {
      platform: 'Microsoft 365 vía Reseller',
      storage: '25 GB/buzón expandible',
      compliance: 'GDPR · Ley 1581 Colombia',
    },
    bestFor: ['Equipo de 5-20 personas', 'Marca que firma contratos digitales', 'E-commerce con atención al cliente'],
  },

  // ======= BUILDER — ÚNICO =======
  {
    id: 'builder-marketing',
    category: 'builder',
    tier_rank: 'medio',
    objectives: ['blog', 'portafolio'],
    tier: 'Websites + Marketing',
    name: 'Builder Plus',
    icon: 'fa-paintbrush',
    tagline: 'Constructor drag-and-drop con marketing integrado. Sin tocar código.',
    pitch: 'Para cuando necesitas salir al aire esta semana. Constructor visual con SEO automático, email marketing y formularios — todo en una suscripción.',
    monthly: 39000,
    yearly: 390000,
    featured: false,
    badge: null,
    features: [
      { label: 'Plantillas', value: '100+ diseños SOTA' },
      { label: 'Constructor', value: 'Drag & drop · móvil-first' },
      { label: 'SEO', value: 'Automático · sitemap dinámico' },
      { label: 'Email marketing', value: '1.000 envíos/mes' },
      { label: 'Formularios', value: 'Ilimitados' },
      { label: 'Social posting', value: 'IG · FB · LinkedIn programados' },
      { label: 'Hosting incluido', value: 'Con dominio gratis 1er año' },
    ],
    specs: {
      engine: 'GoDaddy Websites + Marketing',
      mobile: 'Responsive nativo',
      analytics: 'Google Analytics 4 integrado',
    },
    bestFor: ['Emprendedor sin equipo técnico', 'Profesional independiente', 'Tienda pequeña con < 50 productos'],
  },

  // ======= SERVICIOS GANO — AMBOS =======
  {
    id: 'diagnostico',
    category: 'servicio',
    tier_rank: 'medio',
    objectives: ['agencia', 'corporativo', 'ecommerce'],
    tier: 'Consultoría · Gano Digital',
    name: 'Diagnóstico de Soberanía',
    icon: 'fa-stethoscope',
    tagline: 'Auditoría técnica de tu stack actual. Informe ejecutivo en 72 horas.',
    pitch: 'Antes de migrar a ciegas: un ingeniero SOTA audita tu infraestructura, mide benchmarks reales y entrega un plan de blindaje. Se acredita al contratar cualquier ecosistema.',
    monthly: null,
    yearly: 650000,
    featured: false,
    badge: 'Único pago',
    features: [
      { label: 'Duración', value: '72 h · entrega garantizada' },
      { label: 'Alcance', value: 'Hosting · DNS · Seguridad · SEO técnico' },
      { label: 'Benchmarks', value: 'TTFB · LCP · CLS · auditoría WAF' },
      { label: 'Informe', value: 'PDF ejecutivo · 20-30 páginas' },
      { label: 'Reunión', value: '1 h con ingeniero SOTA' },
      { label: 'Acreditable', value: '100% contra ecosistema anual' },
    ],
    specs: {
      deliverable: 'PDF ejecutivo + grabación de reunión',
      tools: 'WebPageTest · Sucuri · propietarios Gano',
    },
    bestFor: ['Sitio existente con problemas de velocidad', 'Migración planificada', 'Auditoría pre-inversión'],
  },
  {
    id: 'disenio-custom',
    category: 'servicio',
    tier_rank: 'alto',
    objectives: ['agencia', 'corporativo', 'ecommerce'],
    tier: 'Servicio · Diseño a medida',
    name: 'Ecosistema SOTA',
    icon: 'fa-diagram-project',
    tagline: 'Diseño y desarrollo WordPress a medida. Monolito curado por Gano.',
    pitch: 'Desde wireframes hasta despliegue. Tu marca como un producto SOTA: investigación, arquitectura, desarrollo y 3 meses de acompañamiento post-lanzamiento.',
    monthly: null,
    yearly: 8500000,
    featured: false,
    badge: 'A medida',
    features: [
      { label: 'Entregables', value: 'Wireframes · UI · desarrollo · deploy' },
      { label: 'Plazo', value: '6-10 semanas' },
      { label: 'Páginas', value: 'Hasta 12 en el scope inicial' },
      { label: 'Integraciones', value: 'CRM · pasarela · analytics' },
      { label: 'Hosting', value: 'Business NVMe incluido 1er año' },
      { label: 'Acompañamiento', value: '3 meses post-launch' },
    ],
    specs: {
      team: 'Diego + 2 ingenieros SOTA',
      stack: 'WordPress + Elementor + custom code',
      delivery: 'Git + staging + reunión semanal',
    },
    bestFor: ['Marca que necesita diferenciación visual', 'Lanzamiento nuevo', 'Rediseño estratégico'],
  },

  // ======= ACCESO — WordPress Starter =======
  {
    id: 'wp-starter',
    category: 'acceso',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio'],
    tier: 'WordPress Managed · Entrada',
    name: 'WordPress Starter',
    icon: 'fa-seedling',
    tagline: 'Tu primera web WordPress lista en 5 minutos, sin tocar un servidor.',
    pitch: 'Ideal si estás arrancando: WordPress ya viene instalado, el SSL se activa solo y las actualizaciones se hacen automáticas mientras tú te concentras en tu contenido. Sin configuraciones raras, sin código, sin sorpresas.',
    monthly: 15000,
    yearly: 150000,
    featured: false,
    badge: null,
    features: [
      { label: 'Sitios WordPress',   value: '1 sitio incluido' },
      { label: 'Almacenamiento',     value: '30 GB SSD NVMe' },
      { label: 'Tráfico mensual',    value: 'Hasta 25.000 visitas/mes' },
      { label: 'SSL gratuito',       value: 'Incluido y auto-renovado' },
      { label: 'Actualizaciones WP', value: 'Automáticas — sin intervención' },
      { label: 'Staging site',       value: 'Incluido para pruebas seguras' },
      { label: 'Soporte',            value: '24/7 chat y teléfono' },
    ],
    specs: {
      php:       'PHP 8.x (seleccionable)',
      cdn:       'CDN global incluido',
      backups:   'Diarios automáticos',
      wordpress: 'Preinstalado — listo para usar',
    },
    bestFor: ['Blog personal o de contenido', 'Portafolio de diseñador o fotógrafo', 'Landing page de negocio local'],
  },

  // ======= ACCESO — Hosting Compartido Linux =======
  {
    id: 'hosting-basico',
    category: 'acceso',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio'],
    tier: 'Hosting Compartido · Linux',
    name: 'Hosting Compartido Linux',
    icon: 'fa-server',
    tagline: 'Sube tu propio HTML, PHP o MySQL. El mejor punto de partida para aprender.',
    pitch: 'Si estás estudiando programación o quieres montar tu primer proyecto sin un CMS, este hosting te da cPanel completo para subir archivos por FTP, crear bases de datos y probar tu código PHP en un servidor real. Aprendes haciendo.',
    monthly: 9000,
    yearly: 90000,
    featured: false,
    badge: null,
    features: [
      { label: 'Almacenamiento',        value: '10 GB SSD' },
      { label: 'Transferencia mensual', value: '100 GB' },
      { label: 'Panel de control',      value: 'cPanel incluido' },
      { label: 'Base de datos',         value: '1 MySQL incluida' },
      { label: 'Lenguaje',              value: 'PHP 8.x' },
      { label: 'Acceso FTP',            value: 'Incluido' },
      { label: 'Correo corporativo',    value: 'Cuentas de email incluidas' },
    ],
    specs: {
      php:    'PHP 8.x',
      mysql:  'MySQL 8.x',
      acceso: 'FTP / cPanel / SSH (opcional)',
      os:     'Linux (AlmaLinux)',
    },
    bestFor: ['Portafolio estático hecho en HTML y CSS', 'Primer proyecto PHP/MySQL de un estudiante', 'App de gestión académica o inventario básico'],
  },

  // ======= ACCESO — Dominio .com =======
  {
    id: 'dom-com',
    category: 'acceso',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio', 'corporativo'],
    tier: 'Dominio · Registro anual',
    name: 'Dominio .com',
    icon: 'fa-globe',
    tagline: 'Tu nombre en internet. Protegido, tuyo y listo para cualquier sitio.',
    pitch: 'Registra tu .com con privacidad WHOIS incluida para que tu dirección y teléfono no aparezcan en búsquedas públicas. DNS anycast y reenvío de URL sin costo extra. El primer paso para cualquier presencia digital seria.',
    monthly: null,
    yearly: 55000,
    featured: false,
    badge: null,
    features: [
      { label: 'Extensión',          value: '.com — reconocida mundialmente' },
      { label: 'Privacidad WHOIS',   value: 'Incluida — tus datos protegidos' },
      { label: 'DNS anycast',        value: 'Alta velocidad global' },
      { label: 'Reenvío de URL',     value: 'Incluido sin costo extra' },
      { label: 'Renovación',         value: 'Automática — nunca pierdas tu nombre' },
      { label: 'Transferencia',      value: 'Sin costo si decides cambiar de proveedor' },
    ],
    specs: {
      registro:   'ICANN acreditado · GoDaddy Reseller',
      dns:        'Anycast — propagación < 5 min',
      privacidad: 'WHOIS Proxy incluido',
      vigencia:   '1 año renovable',
    },
    bestFor: ['Marca personal o negocio que vende a nivel internacional', 'Empresa colombiana que necesita dirección web profesional', 'Complemento de cualquier plan de hosting para email corporativo'],
  },

  // ======= ACCESO — SSL Estándar DV =======
  {
    id: 'ssl-dv',
    category: 'acceso',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio', 'corporativo', 'ecommerce'],
    tier: 'SSL · Validación de Dominio',
    name: 'SSL Estándar DV',
    icon: 'fa-lock',
    tagline: 'El candado que Google exige y tus clientes confían. En 1 clic.',
    pitch: 'Google penaliza los sitios sin HTTPS y Chrome los marca como "No seguro". Este certificado activa el candado en el navegador, cifra los datos de tus formularios y le dice al cliente que tu sitio es legítimo. Imprescindible si recibes cualquier dato personal.',
    monthly: null,
    yearly: 95000,
    featured: false,
    badge: null,
    features: [
      { label: 'Dominios cubiertos', value: '1 dominio principal' },
      { label: 'Validación',         value: 'DV — Domain Validated' },
      { label: 'Algoritmo',          value: 'SHA-256 · RSA 2048-bit' },
      { label: 'Protocolo',          value: 'TLS 1.2 y TLS 1.3' },
      { label: 'Candado navegador',  value: 'Chrome · Firefox · Safari' },
      { label: 'Instalación',        value: '1 clic desde el panel' },
      { label: 'Garantía',           value: 'Hasta USD $10.000' },
    ],
    specs: {
      validacion:  'DV (Domain Validation)',
      cifrado:     'SHA-256 / RSA 2048-bit',
      protocolos:  'TLS 1.2, TLS 1.3',
      vigencia:    '1 año con renovación automática',
    },
    bestFor: ['Blog o portal que recopila datos de contacto', 'Tienda básica con formulario de pago', 'Área de clientes con login y contraseña'],
  },

  // ======= DEV — WordPress Deluxe =======
  {
    id: 'wp-deluxe',
    category: 'dev',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio', 'corporativo'],
    tier: 'Managed WP · Dev',
    name: 'WordPress Deluxe',
    icon: 'fa-layer-group',
    tagline: '3 sitios independientes con staging. Para freelancers que entregan proyectos de verdad.',
    pitch: 'Maneja desarrollo, staging y producción en un solo plan — o tres clientes simultáneos sin que se mezcle nada. El staging te salva de esa llamada de "¿qué pasó con mi sitio?".',
    monthly: 25000,
    yearly: 250000,
    featured: false,
    badge: null,
    features: [
      { label: 'Sitios WP',         value: '3 instalaciones separadas' },
      { label: 'Almacenamiento',    value: '75 GB NVMe' },
      { label: 'Tráfico mensual',   value: 'Hasta 100.000 visitas' },
      { label: 'Staging',           value: 'Incluido · clon con 1 clic' },
      { label: 'CDN',               value: 'Global · entrega acelerada' },
      { label: 'Backups',           value: 'Cada 24 h · restauración en 1 clic' },
      { label: 'SSL',               value: 'Incluido en cada sitio' },
    ],
    specs: {
      php:   'PHP 8.x administrado',
      db:    'MySQL 8.0 · base por sitio',
      cache: 'OPcache + caché de página',
      tls:   'TLS 1.3',
      panel: 'cPanel simplificado GoDaddy',
    },
    bestFor: ['Freelancer con 2-3 clientes activos', 'Agencia pequeña en crecimiento', 'Dev que usa staging para probar antes de publicar'],
  },

  // ======= DEV — Web Hosting Plus cPanel =======
  {
    id: 'hosting-plus-dev',
    category: 'dev',
    tier_rank: 'bajo',
    objectives: ['portafolio', 'corporativo'],
    tier: 'Web Hosting Plus · Dev',
    name: 'Web Hosting Plus · Dev',
    icon: 'fa-code',
    tagline: 'cPanel con SSH, PHP 8.x, MySQL, Python y cronjobs. Control real sin complejidad de VPS.',
    pitch: 'Cuando WordPress se te queda corto. SSH abierto, PHP + Python + Node.js básico en el mismo servidor, cronjobs para tus automatizaciones, y subdominios ilimitados para cada proyecto.',
    monthly: 19000,
    yearly: 190000,
    featured: false,
    badge: null,
    features: [
      { label: 'Almacenamiento', value: '50 GB SSD' },
      { label: 'SSH',            value: 'Acceso completo activado' },
      { label: 'Bases de datos', value: 'MySQL ilimitadas' },
      { label: 'Lenguajes',      value: 'PHP 8.x · Python 3 · Node.js básico' },
      { label: 'Cronjobs',       value: 'Ilimitados · editor visual' },
      { label: 'Subdominios',    value: 'Ilimitados · DNS instantáneo' },
      { label: 'Git',            value: 'Desde terminal vía SSH' },
    ],
    specs: {
      php:    'PHP 8.1 / 8.2 seleccionable por dominio',
      mysql:  'MySQL 8.0 · phpMyAdmin incluido',
      python: 'Python 3.11 · pip disponible',
      node:   'Node.js 20 LTS · uso básico',
      panel:  'cPanel Linux · acceso completo',
    },
    bestFor: ['Dev PHP/Python con proyectos custom', 'Estudiante avanzado que necesita servidor real', 'App de gestión o inventario para negocio colombiano'],
  },

  // ======= DEV — Email Starter =======
  {
    id: 'email-starter',
    category: 'dev',
    tier_rank: 'bajo',
    objectives: ['blog', 'portafolio'],
    tier: 'Correo profesional · Starter',
    name: 'Email Starter',
    icon: 'fa-envelope',
    tagline: 'tu@tunegocio.com desde el primer día. DKIM, SPF y compatible con Outlook y Gmail.',
    pitch: 'Un buzón profesional con tu dominio. Sin pagar por 5 cuentas que no usas. DKIM y SPF ya configurados para que tus correos lleguen a la bandeja, no al spam.',
    monthly: 6000,
    yearly: 60000,
    featured: false,
    badge: null,
    features: [
      { label: 'Buzones incluidos', value: '1 cuenta profesional' },
      { label: 'Espacio',           value: '10 GB por buzón' },
      { label: 'Dominio propio',    value: 'tu@tunegocio.com' },
      { label: 'Protocolo',         value: 'IMAP · POP3 · SMTP' },
      { label: 'Anti-spam',         value: 'DKIM · SPF configurados' },
      { label: 'Webmail',           value: 'Acceso desde navegador' },
      { label: 'Clientes',          value: 'Outlook · Gmail · Thunderbird' },
    ],
    specs: {
      storage:  '10 GB expandible',
      auth:     'DKIM + SPF + DMARC básico',
      access:   'IMAP / POP3 / SMTP estándar',
      webmail:  'Roundcube o Horde incluido',
      mobile:   'iOS · Android nativo',
    },
    bestFor: ['Freelancer independiente que quiere correo serio', 'Emprendedor unipersonal con dominio propio', 'Dev con portafolio que firma propuestas por correo'],
  },
];

// ======= GLOSARIO =======
window.GANO_GLOSSARY = {
  'NVMe Gen4': { title: 'NVMe Gen4', body: 'Non-Volatile Memory Express sobre PCIe 4.0. Hasta 7.500 MB/s — 15× más rápido que un SSD SATA. Se traduce en cargas WordPress 3-5× más veloces.', metric: '7.500 MB/s' },
  'WAF Capa 7': { title: 'WAF Capa 7', body: 'Firewall que opera en la capa de aplicación HTTP/HTTPS. Bloquea SQL injection, XSS, CSRF y bots antes de que toquen tu WordPress.', metric: 'OWASP Top 10' },
  'TLS 1.3': { title: 'TLS 1.3', body: 'Protocolo que cifra HTTPS. Handshake más rápido (1-RTT), cifras obsoletas eliminadas, resistencia post-cuántica opcional.', metric: '1-RTT handshake' },
  'CDN': { title: 'CDN Global', body: 'Red de servidores distribuidos que sirve tu contenido desde el POP más cercano al visitante. Reduce latencia 60-80% en audiencias internacionales.', metric: '200+ POPs' },
  'Object Cache': { title: 'Object Cache (Redis)', body: 'Caché en RAM para queries repetitivas de WordPress. Evita que cada visita pegue a MySQL. Soporta 10× más tráfico sin degradarse.', metric: 'RAM-speed access' },
  'Nodo Bogotá': { title: 'Nodo Alpha Bogotá', body: 'Centro de datos en Colombia. Latencia <20ms para usuarios locales. Cumple Ley 1581 de protección de datos.', metric: '<20ms latencia local' },
  'WHOIS': { title: 'Privacidad WHOIS', body: 'Base de datos pública del dueño de un dominio. Sin privacidad, tu teléfono y dirección quedan expuestos. Gano activa privacidad WHOIS gratis, siempre.', metric: 'Datos protegidos' },
  'SLA 99.95%': { title: 'SLA 99.95%', body: 'Service Level Agreement. 99.95% de uptime permite máximo 21.6 min de caída al mes. Si incumplimos, se acredita proporcional.', metric: '21.6 min/mes máx' },
  'TTFB': { title: 'TTFB', body: 'Time to First Byte: tiempo entre que el navegador pide la página y recibe el primer byte. Google recomienda <200ms. Gano promedia 45-80ms.', metric: 'Target: <200ms' },
  'DDoS': { title: 'Mitigación DDoS', body: 'Ataques que saturan tu servidor con tráfico falso. Gano mitiga hasta 10 Gbps en capa de red + filtrado inteligente en capa 7.', metric: 'Hasta 10 Gbps' },
  'Post-Cuántico': { title: 'Cifrado Post-Cuántico', body: 'Algoritmos diseñados para resistir ataques de computadoras cuánticas. Kyber-768 opt-in en nodo Alpha Bogotá.', metric: 'Kyber-768' },
};

// ======= TIMELINE =======
window.GANO_TIMELINE = [
  { t: '0 min', title: 'Firma y pago', body: 'Cobro en COP por GoDaddy Reseller. Factura electrónica al instante.', icon: 'fa-file-signature' },
  { t: '2 min', title: 'Aprovisionamiento', body: 'Tu nodo se activa en Alpha Bogotá. Credenciales por correo cifrado.', icon: 'fa-bolt' },
  { t: '5 min', title: 'Vinculación DNS', body: 'DNS configurado por el Agente IA. Propagación acelerada vía Anycast.', icon: 'fa-globe' },
  { t: '10 min', title: 'WordPress listo', body: 'Instalación, SSL, WAF y backups activos. Ya puedes publicar.', icon: 'fa-wordpress', iconBrand: true },
  { t: '24 h', title: 'Llamada de bienvenida', body: 'Diego o un ingeniero SOTA revisa tus objetivos y responde dudas.', icon: 'fa-headset' },
  { t: '7 días', title: 'Primer checkpoint', body: 'Revisión de métricas. Ajustes de cacheo y WAF según tu tráfico real.', icon: 'fa-chart-line' },
  { t: 'Siempre', title: 'Agente IA 24/7', body: 'Gano Agent disponible para cualquier consulta técnica o de facturación.', icon: 'fa-robot' },
];

// ======= OBJETIVOS =======
window.GANO_OBJECTIVES = [
  { id: 'all',        label: 'Todos',       icon: 'fa-asterisk' },
  { id: 'blog',       label: 'Blog',        icon: 'fa-feather-pointed' },
  { id: 'portafolio', label: 'Portafolio',  icon: 'fa-image' },
  { id: 'corporativo',label: 'Corporativo', icon: 'fa-building' },
  { id: 'ecommerce',  label: 'E-commerce',  icon: 'fa-store' },
  { id: 'agencia',    label: 'Agencia',     icon: 'fa-sitemap' },
];

// ======= CATEGORÍAS =======
window.GANO_CATEGORIES = [
  { id: 'all',      label: 'Todos',            icon: 'fa-asterisk' },
  { id: 'hosting',  label: 'Hosting WP',       icon: 'fa-microchip' },
  { id: 'vps',      label: 'VPS · Servidores', icon: 'fa-server' },
  { id: 'dominio',  label: 'Dominios',         icon: 'fa-globe' },
  { id: 'seguridad',label: 'Seguridad',        icon: 'fa-shield-halved' },
  { id: 'email',    label: 'Email',            icon: 'fa-envelope' },
  { id: 'builder',  label: 'Builder',          icon: 'fa-paintbrush' },
  { id: 'servicio', label: 'Servicios Gano',   icon: 'fa-handshake' },
  { id: 'acceso',   label: 'Acceso · Empezar', icon: 'fa-seedling' },
  { id: 'dev',      label: 'Para Desarrolladores', icon: 'fa-code' },
];

// Format helpers
window.formatCOP = function(n) {
  if (n == null) return '—';
  if (n >= 1000000) return '$' + (n / 1000000).toFixed(n % 1000000 === 0 ? 0 : 1).replace('.', ',') + 'M';
  if (n >= 1000) return '$' + Math.round(n / 1000) + 'K';
  return '$' + n;
};
window.formatCOPFull = function(n) {
  if (n == null) return '—';
  return '$' + n.toLocaleString('es-CO');
};
